project:
  type: website
  output-dir: docs

website:
  title: "Kyle Gontjes"
  navbar:
    background: primary
    search: true
    tools:
      - icon: twitter
        href: https://x.com/KyleGontjes
      - icon: github
        href: https://github.com/kylegontjes
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: software.qmd
        text: Software
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual 

execute:
  freeze: auto
