---
title: "About me"
---

## Biography

A native of Grand Rapids, I graduated from [Calvin University](http://www.calvin.edu/) in 2017 with a BSc in Biology.\
\
I followed my passion for infection prevention to the [University of Michigan School of Public Health](https://sph.umich.edu/), where I completed an MPH in Hospital & Molecular Epidemiology in 2020. During my MPH, I worked for [Dr. Lona Mody](https://criisp-mody.lab.medicine.umich.edu/home), of the Division of Geriatric & Palliative Medicine, studying the infection prevention and epidemiology of antibiotic-resistant bacteria in hospitals and nursing homes. We continue to collaborate, with a current focus on capturing young adult voices on public health and health education.\
\
I did my PhD in Microbiology & Immunology at the University of Michigan Medical School. I worked with [Dr. Evan Snitkin](https://medschool.umich.edu/profile/3206/evan-s-snitkin) and [Dr. Ebbing Lautenbach](https://www.med.upenn.edu/apps/faculty/index.php/g275/p10014) to leverage clinical metadata and whole-genome sequencing to study the emergence and spread of multidrug-resistant organisms in hospital and community settings.

After finishing my PhD, I joined the research faculty at the University of Michigan. I started as a Research Investigator in Dr. Snitkin's laboratory in August, 2026. I am excited to build upon my dissertation research and spend my career advancing our ability to perform high-impact, clinically-relevant molecular epidemiology research.

## Research interests

My career goal is to develop innovative solutions to combat antibiotic resistance by combining advanced genomic approaches, data analysis, and wet lab experimentation to identify patient and bacterial features that drive the emergence and spread of antibiotic resistance.

::::: columns
::: {.column width="50%"}
My interests:

1.  Evolution of antibiotic resistance

2.  Transmission of antibiotic-resistant organisms

3.  Phylogenetics of bacterial genome-influenced traits

4.  Epidemiologic trends of antibiotic-resistant organisms

5.  Translational infection prevention research
:::

::: {.column width="50%"}
Methods of interest:

1.  Whole-genome sequencing

2.  Epidemiological study designs

3.  Statistical genomics and phylogenetics

4.  Bioinformatic tool and pipeline development for molecular epidemiology

5.  Experimental validation of genomic observations
:::
:::::

## Skills

1.  **Software:** Microsoft Office, Adobe Creative Suite, BioRender, DropBox, and Google Suites
2.  **Programming:** R, Linux, SAS, Python, GitHub, Docker/Singularity, SLURM (high-performance computing cluster)
3.  **Molecular epidemiology:** Whole-genome sequencing, variant calling, gene identification, pangenomics, phylogenetics
4.  **Statistical methods:** Ancestral state reconstruction, convergence-based genome-wide association studies, burden testing, regression modeling
5.  **Wet lab experimentation:** Specimen collection, bacterial cultivation, identification, and susceptibility testing
