---
title: "Research"
---

My research uses clinical metadata and whole-genome sequencing to study the evolution and spread of antibiotic resistant bacteria in hospital and community settings.

For the complete list of my publications, please visit my [Google Scholar profile](https://scholar.google.com/citations?user=hG4WnBEAAAAJ&hl=en).

# **Microbial evolution**

I leverage whole-genome sequencing data, phylogenetics, and epidemiological methods to evaluate the evolution of bacterial pathogens.\
Primarily focusing on the evolution and spread of antibiotic resistance, I am also interested in other genome-influenced traits like virulence and infection dynamics.

1.  **Gontjes K**, Singh A, Sansom SE, Boyko J, Smith SA, Lautenbach E, Snitkin E. Phylogenetic context of antibiotic resistance provides insights into the dynamics of resistance emergence and spread. *Journal of Infectious Diseases.* 2025. [link](https://doi.org/10.1093/infdis/jiaf478)
2.  **Gontjes K**, ..., Lautenbach E, Snitkin E. Identifying drivers of β-lactam/β-lactamase inhibitor resistance emergence and spread before their clinical deployment. medRxiv. [link](https://www.medrxiv.org/content/10.1101/2025.07.29.25331838v1.full)
3.  Boyko J, **Gontjes K,** Snitkin E, Smith SA. Uncertainty in joint ancestral state reconstruction: Improving accuracy and biological interpretability of ancestral state prediction. Accepted at PNAS. [link](https://www.biorxiv.org/content/10.1101/2025.10.09.681367v1)
4.  Unverdorben LV, Pirani A, **Gontjes K**, Moricz B, Holmes CH, Snitkin ES, Bachman MA. Klebsiella pneumoniae evolution in the gut leads to spontaneous capsule loss and decreased virulence potential. *mBio*, 2025. [link](https://doi.org/10.1128/mbio.02362-24)

# Microbial genomic epidemiology

I leverage observational and intervention studies to evaluate the distribution and determinants of colonization and infection with antibiotic-resistant organisms.

1.  Lapp Z, … **Gontjes K**, …, Evan Snitkin, Rachel B Slayton. Distinct Origins and Transmission Pathways of blaKPC Enterobacterales across Three U.S. States. *J Clin Microbiol*. 2023. [link](https://doi.org/10.1128/jcm.00259-23)
2.  Zhang HL, **Gontjes K,** Han JH, Alby K, Lapp Z, Snitkin S, Goldstein EJC, Muldoon S, Tolomeo P, Lautenbach E. Resistance phenotypes of carbapenem-resistant Klebsiella pneumoniae in a multi-state network of long-term acute care hospitals. *Infect Control Hosp Epidemiol*. 2022. [link](https://doi.org/10.1017/ice.2022.185)

# Translational infection prevention research

Alongside my research on the genomic epidemiology of antibiotic-resistance organisms, I have also conducted translational infection prevention research to characterize the epidemiology and risk factors for colonization with antibiotic-resistant bacteria.

1.  **Gontjes K**, Gibson KE, Lansing B, Karen J, Cassone M, Wang J, Mills J, Mody L, Patel K. Association of exposure to high-risk antibiotics in acute care hospitals with multidrug-resistant organism burden in nursing homes. *JAMA Network Open*, 2022. [link](https://doi.org/10.1001/jamanetworkopen.2021.44959)
2.  Mody L, **Gontjes K,** Cassone M, Gibson KE, Lansing B, Mantey J, Kabeto M, Galecki A, Min L. Effectiveness of a Multicomponent Intervention to Reduce Multidrug-Resistant Organisms in Nursing Homes: A Cluster Randomized Clinical Trial. *JAMA Network Open,* 2021. [link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8285736/)
3.  **Gontjes K**, Gibson KE, Lansing B, Mody L, Cassone M. Can alternative anatomical sites and environmental surveillance replace perianal screening for multidrug-resistant organisms in nursing homes? *Infect Control Hosp Epidemiol*, 2021. [link](https://doi.org/10.1017/ice.2021.134)
4.  **Gontjes K**, Gibson KE, Lansing B, Mody L, Cassone M. Assessment of Race and Sex as Risk Factors for Colonization with Multidrug-Resistant Organisms in Six Nursing Homes. *Infect Control Hosp Epidemiol*, 2020. [link](https://doi.org/10.1017/ice.2020.215)
5.  **Gontjes K,** Gibson KE, Lansing B, Cassone M, Mody L. Contamination of Common Area and Rehabilitation Gym Environment with Multidrug-Resistant Organisms. J Am Geriatric Soc., 2020. [link](https://doi.org/10.1111/jgs.16284)

# **Public health education**

Alongside my genomic epidemiology research, I am interest in understanding interest and confidence in public health.\
To accomplish this, I have led the deployment of two surveys to gauge young adult voices on public health, health education, and infection prevention related topics.

1.  Mody M, **Gontjes K.** Health Education After COVID-19: A Time to Revisit, Revamp, and Revitalize? *A J Infect Control*, 2022. [link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8446583/)
2.  Mody M, Hodges AN, Gibson KE, Mantey J, **Gontjes K**. Does high school health education class satisfaction influence student perceptions of public health and pandemic response? *A J Infect Control*. 2024. [link](https://doi.org/10.1016/j.ajic.2024.01.008)

# Cultural commentaries

I also enjoy writing about a variety of topics. I’ve published commentaries on the role of grace in medicine.\
Feel free to reach out if you’d like to discuss these subjects or collaborate on a commentary!

1.  **Gontjes K,** Collier K. From a Culture of Blame to a Culture of Grace: A Letter in Reply to Papadakis. *Infect Control Hosp Epidemiol*, August 2021. [link](https://doi.org/10.1017/ice.2021.386)
